# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Heydar Soudani
title: PhD candidate @ Radboud University | Information Retrieval | Large language models | Data Generation | Retrieval Augmented Generation | Uncertainty Estimation
email: heydar.soudani@ru.nl
website: www.heydar_soudani.github.io/

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: arian_ask
github_username:  HeydarSoudani
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: arian.askarii
linkedin_username: heydar-soudani
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000
# additional_links:
# - title: scholar link
#   icon: fas fa-box-archive
#   url: https://scholar.google.com/citations?user=fp9QtoEAAAAJ&hl=en

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  As a PhD candidate and a Marie Skłodowska-Curie Research Fellow at Leiden University, I study large language models from a retrieval point of view and develop effective retrieval models for web and professional search. I have over four years of experience in data engineering, back-end development, and software engineering. I have published multiple papers at prestigious conferences during my PhD and MSc. My passion lies in pushing the boundaries of information retrieval through the capabilities of LLMs, while also applying these advancements to real-world issues and practical applications.
  
  I am also a Visiting Researcher at the University of Amsterdam where I do research in collaboration with Evangelos Kanoulas and Mohammad Aliannejadi. My initial project during this visit delved into a research on conversational search in the legal domain, and its outcome is recently published at CIKM 2023 long paper track. Currently, my research revolves around the training and analyzing Large Language Models (LLMs) for text retrieval tasks and the early outcome of it is a resource paper at CIKM titled "A Test Collection of Synthetic Documents for Training Rankers: ChatGPT vs. Human Experts" that analyze whether ChatGPT's responses can act as training data for Q&A retrieval models.

Find me on [Linkedin](https://www.linkedin.com/in/heydar-soudani-2b7650144/), [GitHub](https://github.com/HeydarSoudani/), or email me: heydar.soudani@ru.nl


content:
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      To be written!
# Alongside my interests in networks and software engineering some of my other interests and hobbies are:
# - Rock climbing
# - Gaming
# - Knitting
# - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Look at this cool image  
# ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag


